language: none  # 특별한 언어가 필요하지 않음

deploy:
  provider: pages  # GitHub Pages에 배포
  skip_cleanup: true  # 빌드 후 클린업을 하지 않음
  github_token: $GITHUB_TOKEN  # GitHub token을 환경 변수로 설정
  local_dir: ./  # HTML 파일이 있는 디렉터리 (현재 디렉터리)
  on:
    branch: master  # main 브랜치에서만 배포 (필요한 경우 다른 브랜치로 변경)
